#:schema node_modules/wrangler/config-schema.json
name = "sublink-dingyuezhuanhuan"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "19b615ffca2d4cb5aaf2a4a71694c3d2" }
]

[assets]
directory = "./public"
